name = "GLFWAbstraction"
uuid = "b4519675-ec9c-4dd5-a759-fbb42bea0e46"
authors = ["Kiruse <contact@kiruse.dev>"]
version = "0.2.1"

[deps]
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GenerateProperties = "ad744131-fa5b-4912-8d03-4395d7e5240b"
KirUtil = "35055d32-6816-4a65-8aeb-d6e3aca393e8"

[compat]
BitFlags = "0.1.3"
GLFW = "3.4.1"
GenerateProperties = "0.1"
julia = "1.6"
KirUtil = "0.1.0"
